name: expense
networks: # this is global can use by any below  var
  default:
    name: expense
services:
  mysql:
    image: mysql:v1.0
    container_name: mysql # --name mysql
  backend:
    image: backend:v1.0
    container_name: backend
    depends_on: # depends_on --> is always a list
      - mysql
  frontend:
    image: frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      -"80:80"