version: '3.8'
name: expense
networks: # this is global can use by any below  var
  default:
    name: expense
volumes:
  mysql: # this is docker volume create mysql
  volumes:
    - mysql:/var/lib/mysql  # -v volume-name:/path/in/container
services:
  mysql:
    image: mysql:v1.0
    container_name: mysql # --name mysql
  backend:
    image: backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js" # sleep? mysql takes time to create schema...
    depends_on: # depends_on --> is always a list
      - mysql
  frontend:
    image: frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"